import { SALE_KEYS } from "../types/key";

export const FilterOperator = {
  IS_NOT: "is not",
  CONTAINS: "contains",
  DOES_NOT_CONTAIN: "does not contain",
  STARTS_WITH: "starts with",
  ENDS_WITH: "ends with",
  IS_EMPTY: "is empty",
  IS_NOT_EMPTY: "is not empty",

  IS: "is",

  IS_BEFORE: "is before",
  IS_AFTER: "is after",
  IS_ON_OR_BEFORE: "is on or before",
  IS_ON_OR_AFTER: "is on or after",
  //   IS_BETWEEN: "is between",
  //   IS_RELATIVE_TO_TODAY: "is relative to today",

  "=": "=",
  "!=": "!=",
  "<": "<",
  ">": ">",
  "<=": "<=",
  ">=": ">=",
};

export enum DateOption {
  TODAY = "Today",
  TOMORROW = "Tomorrow",
  YESTERDAY = "Yesterday",
  ONE_WEEK_AGO = "One week ago",
  ONE_WEEK_FROM_NOW = "One week from now",
  ONE_MONTH_AGO = "One month ago",
  ONE_MONTH_FROM_NOW = "One month from now",
  CUSTOM_DATE = "Custom date",
}

export const FILTER_OPTIONS = {
  [SALE_KEYS.COMPANY]: [
    FilterOperator.IS,
    FilterOperator.IS_NOT,
    FilterOperator.CONTAINS,
    FilterOperator.DOES_NOT_CONTAIN,
    FilterOperator.STARTS_WITH,
    FilterOperator.ENDS_WITH,
    FilterOperator.IS_EMPTY,
    FilterOperator.IS_NOT_EMPTY,
  ],
  [SALE_KEYS.PRIORITY]: [
    FilterOperator.IS,
    FilterOperator.IS_NOT,
    FilterOperator.IS_EMPTY,
    FilterOperator.IS_NOT_EMPTY,
  ],
  [SALE_KEYS.TAG]: [
    FilterOperator.CONTAINS,
    FilterOperator.DOES_NOT_CONTAIN,
    FilterOperator.IS_EMPTY,
    FilterOperator.IS_NOT_EMPTY,
  ],
  [SALE_KEYS.ESTIMATED_VALUE]: [
    FilterOperator["="],
    FilterOperator["!="],
    FilterOperator["<"],
    FilterOperator[">"],
    FilterOperator["<="],
    FilterOperator[">="],
    FilterOperator.IS_EMPTY,
    FilterOperator.IS_NOT_EMPTY,
  ],
  [SALE_KEYS.ACCOUNT_OWNER]: [
    FilterOperator.CONTAINS,
    FilterOperator.DOES_NOT_CONTAIN,
    FilterOperator.IS_EMPTY,
    FilterOperator.IS_NOT_EMPTY,
  ],
  [SALE_KEYS.STATUS]: [FilterOperator.IS, FilterOperator.IS_NOT, FilterOperator.IS_EMPTY, FilterOperator.IS_NOT_EMPTY],
  [SALE_KEYS.NAME]: [
    FilterOperator.IS,
    FilterOperator.IS_NOT,
    FilterOperator.CONTAINS,
    FilterOperator.DOES_NOT_CONTAIN,
    FilterOperator.STARTS_WITH,
    FilterOperator.ENDS_WITH,
    FilterOperator.IS_EMPTY,
    FilterOperator.IS_NOT_EMPTY,
  ],
  [SALE_KEYS.DONE]: [FilterOperator.IS, FilterOperator.IS_NOT],
  [SALE_KEYS.FOLLOW_UP_DATE]: [
    FilterOperator.IS,
    FilterOperator.IS_BEFORE,
    FilterOperator.IS_AFTER,
    FilterOperator.IS_ON_OR_BEFORE,
    FilterOperator.IS_ON_OR_AFTER,
    FilterOperator.IS_EMPTY,
    FilterOperator.IS_NOT_EMPTY,
  ],
  [SALE_KEYS.CREATED_TIME]: [
    FilterOperator.IS,
    FilterOperator.IS_BEFORE,
    FilterOperator.IS_AFTER,
    FilterOperator.IS_ON_OR_BEFORE,
    FilterOperator.IS_ON_OR_AFTER,
    FilterOperator.IS_EMPTY,
    FilterOperator.IS_NOT_EMPTY,
    // FilterOperator.IS_BETWEEN,
    // FilterOperator.IS_RELATIVE_TO_TODAY,
  ],
  [SALE_KEYS.LAST_EDITED_TIME]: [
    FilterOperator.IS,
    FilterOperator.IS_BEFORE,
    FilterOperator.IS_AFTER,
    FilterOperator.IS_ON_OR_BEFORE,
    FilterOperator.IS_ON_OR_AFTER,
    FilterOperator.IS_EMPTY,
    FilterOperator.IS_NOT_EMPTY,
    // FilterOperator.IS_BETWEEN,
    // FilterOperator.IS_RELATIVE_TO_TODAY,
  ],
};
