import { SALE_KEYS } from "../types/key";

export const KEY_NAME_MAP = {
  [SALE_KEYS.NONE]: "Select a property",
  [SALE_KEYS.NAME]: "Name",
  [SALE_KEYS.COMPANY]: "Company",
  [SALE_KEYS.PRIORITY]: "Priority",
  [SALE_KEYS.STATUS]: "Status",
  [SALE_KEYS.ESTIMATED_VALUE]: "Est value",
  [SALE_KEYS.ACCOUNT_OWNER]: "Acc owner",
  [SALE_KEYS.TAG]: "Tag",
  [SALE_KEYS.DONE]: "Done",
  [SALE_KEYS.FOLLOW_UP_DATE]: "Follow Up Date",
  [SALE_KEYS.CREATED_TIME]: "Created time",
  [SALE_KEYS.LAST_EDITED_TIME]: "Last edited time",
} as const;

export const SORT_KEYS: Record<SALE_KEYS, string> = {
  [SALE_KEYS.NONE]: KEY_NAME_MAP[SALE_KEYS.NONE],
  [SALE_KEYS.NAME]: KEY_NAME_MAP[SALE_KEYS.NAME],
  [SALE_KEYS.COMPANY]: KEY_NAME_MAP[SALE_KEYS.COMPANY],
  [SALE_KEYS.PRIORITY]: KEY_NAME_MAP[SALE_KEYS.PRIORITY],
  [SALE_KEYS.STATUS]: KEY_NAME_MAP[SALE_KEYS.STATUS],
  [SALE_KEYS.ESTIMATED_VALUE]: "Estimated value",
  [SALE_KEYS.ACCOUNT_OWNER]: "Account owner",
  [SALE_KEYS.TAG]: KEY_NAME_MAP[SALE_KEYS.TAG],
  [SALE_KEYS.DONE]: KEY_NAME_MAP[SALE_KEYS.DONE],
  [SALE_KEYS.FOLLOW_UP_DATE]: KEY_NAME_MAP[SALE_KEYS.FOLLOW_UP_DATE],
  [SALE_KEYS.CREATED_TIME]: KEY_NAME_MAP[SALE_KEYS.CREATED_TIME],
  [SALE_KEYS.LAST_EDITED_TIME]: KEY_NAME_MAP[SALE_KEYS.LAST_EDITED_TIME],
} as const;
